# version: '3.8'

services:
  frontend:
    build:
      context: . 
      dockerfile: Dockerfile_frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  backend:
    build: 
      context: . 
      dockerfile: Dockerfile_backend
      target: backend
    # container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pursuiter
    # volumes:
      # - ./backend:/app  # Map the entire backend directory
      # - /app/node_modules  # Ensure node_modules is managed within the container

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo-data:/data/db